name: google_places_sdk_plus_web
description: The web implementation of Flutter plugin for google places sdk
version: 0.4.0
homepage: https://github.com/KamiloChinome/google_places_sdk_plus/tree/master/google_places_sdk_plus_web

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  google_maps: ^8.2.0
  google_places_sdk_plus_platform_interface: ^0.5.0
  web: ^1.1.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        fileName: google_places_sdk_plus_web.dart
        pluginClass: FlutterGooglePlacesSdkWebPlugin
