name: google_places_sdk_plus
description: A Flutter plugin for google places sdk that uses the native libraries on each platform
version: 0.5.4
homepage: https://github.com/KamiloChinome/google_places_sdk_plus/tree/master/google_places_sdk_plus

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  google_places_sdk_plus_platform_interface: ^0.5.0
  google_places_sdk_plus_ios: ^0.3.0
  google_places_sdk_plus_web: ^0.4.0
  google_places_sdk_plus_android: ^0.4.0
  google_places_sdk_plus_windows: ^0.4.0
  google_places_sdk_plus_linux: ^0.4.0
  google_places_sdk_plus_macos: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        default_package: google_places_sdk_plus_android
      ios:
        default_package: google_places_sdk_plus_ios
      web:
        default_package: google_places_sdk_plus_web
      windows:
        default_package: google_places_sdk_plus_windows
      linux:
        default_package: google_places_sdk_plus_linux
      macos:
        default_package: google_places_sdk_plus_macos
