name: google_places_sdk_plus_android
description: A Flutter plugin for google places sdk that uses the native libraries on each platform
version: 0.4.0
homepage: https://github.com/KamiloChinome/google_places_sdk_plus/tree/master/google_places_sdk_plus_android

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  google_places_sdk_plus_platform_interface: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.google_places_sdk_plus
        pluginClass: FlutterGooglePlacesSdkPlugin
