name: google_places_sdk_plus_http
description: An http implementation of Flutter plugin to be used by other platform implementation
version: 0.4.0
homepage: https://github.com/KamiloChinome/google_places_sdk_plus/tree/master/google_places_sdk_plus_http

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  google_places_sdk_plus_platform_interface: ^0.5.0
  http: ^1.6.0
  json_annotation: ^4.9.0
  latlong2: ^0.9.1

dev_dependencies:
  build_runner: ^2.10.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  mockito: ^5.4.0
