name: google_places_sdk_plus_windows
description: The windows implementation of Flutter plugin for google places sdk
version: 0.4.0
homepage: https://github.com/KamiloChinome/google_places_sdk_plus/tree/master/google_places_sdk_plus_windows

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  google_places_sdk_plus_platform_interface: ^0.5.0
  google_places_sdk_plus_http: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    implements: google_places_sdk_plus
    platforms:
      windows:
        fileName: google_places_sdk_plus_windows.dart
        dartPluginClass: FlutterGooglePlacesSdkWindowsPlugin
