name: flutter_google_places_sdk_windows
description: The windows implementation of Flutter plugin for google places sdk
version: 0.4.0
homepage: https://github.com/matanshukry/flutter_google_places_sdk/tree/master/flutter_google_places_sdk_windows

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_google_places_sdk_platform_interface: ^0.5.0
  flutter_google_places_sdk_http: ^0.4.0

dependency_overrides:
  flutter_google_places_sdk_platform_interface:
    path: ../flutter_google_places_sdk_platform_interface
  flutter_google_places_sdk_http:
    path: ../flutter_google_places_sdk_http

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    implements: flutter_google_places_sdk
    platforms:
      windows:
        fileName: flutter_google_places_sdk_windows.dart
        dartPluginClass: FlutterGooglePlacesSdkWindowsPlugin
