name: google_places_sdk_plus_macos
description: The macos implementation of Flutter plugin for google places sdk
version: 0.4.0
homepage: https://github.com/KamiloChinome/google_places_sdk_plus/tree/master/google_places_sdk_plus_macos

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  google_places_sdk_plus_http: ^0.4.0
  google_places_sdk_plus_platform_interface: ^0.5.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: google_places_sdk_plus
    platforms:
      macos:
        fileName: google_places_sdk_plus_macos.dart
        dartPluginClass: FlutterGooglePlacesSdkMacosPlugin
